### ISSUE TITLE
Legacy Mti-G does not publish UTC Time

### ISSUE THREAD

**Issue by ozgunkaratas** [ethz-asl/ethzasl_xsens_driver#112]
Hello,
i am using a Legacy Mti-G device on Ubuntu 18.04 with Melodic and i was able to use the legacy configurations to get the information but when i include the UTC Time within the output settings i get a parsing error. The console output is as follows:

ozgunkaratas@ozgunkaratas-1804:~$ roslaunch xsens_driver xsens_driver.launch
... logging to /home/ozgunkaratas/.ros/log/d2f883be-2e81-11eb-921e-b0fc36b70e8b/roslaunch-ozgunkaratas-1804-9645.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://ozgunkaratas-1804:39703/

SUMMARY

========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /xsens_driver/angular_velocity_covariance_diagonal: [0.0004, 0.0004, ...
 * /xsens_driver/baudrate: 0
 * /xsens_driver/device: auto
 * /xsens_driver/frame_id: /imu
 * /xsens_driver/frame_local: ENU
 * /xsens_driver/initial_wait: 0.1
 * /xsens_driver/linear_acceleration_covariance_diagonal: [0.0004, 0.0004, ...
 * /xsens_driver/no_rotation_duration: 0
 * /xsens_driver/orientation_covariance_diagonal: [0.01745, 0.01745...
 * /xsens_driver/timeout: 0.002
NODES
  /
    xsens_driver (xsens_driver/mtnode.py)
ROS_MASTER_URI=http://localhost:11311
process[xsens_driver-1]: started with pid [9660]
[INFO] [1606245725.124993]: Found parameter: ~device, value: auto
[INFO] [1606245725.127938]: Found parameter: ~baudrate, value: 0
[INFO] [1606245725.130486]: Found parameter: ~timeout, value: 0.002
[INFO] [1606245725.133216]: Found parameter: ~initial_wait, value: 0.1
[INFO] [1606245725.329703]: Detected MT device on port /dev/ttyUSB0 @ 115200 bps
[INFO] [1606245725.331874]: MT node interface: /dev/ttyUSB0 at 115200 bd.
[INFO] [1606245725.506297]: Found parameter: ~no_rotation_duration, value: 0
[INFO] [1606245725.509225]: Found parameter: ~frame_id, value: /imu
[INFO] [1606245725.512022]: Found parameter: ~frame_local, value: ENU
[INFO] [1606245725.514789]: Found parameter: ~angular_velocity_covariance_diagonal, value: [0.0004, 0.0004, 0.0004]
[INFO] [1606245725.517435]: Found parameter: ~linear_acceleration_covariance_diagonal, value: [0.0004, 0.0004, 0.0004]
[INFO] [1606245725.520709]: Found parameter: ~orientation_covariance_diagonal, value: [0.01745, 0.01745, 0.15708]
Traceback (most recent call last):
  File "/home/ozgunkaratas/catkin_ws/src/ethzasl_xsens_driver-master/nodes/mtnode.py", line 803, in <module>
    main()
  File "/home/ozgunkaratas/catkin_ws/src/ethzasl_xsens_driver-master/nodes/mtnode.py", line 799, in main
    driver.spin()
  File "/home/ozgunkaratas/catkin_ws/src/ethzasl_xsens_driver-master/nodes/mtnode.py", line 168, in spin
    self.spin_once()
  File "/home/ozgunkaratas/catkin_ws/src/ethzasl_xsens_driver-master/nodes/mtnode.py", line 710, in spin_once
    data = self.mt.read_measurement()
  File "/home/ozgunkaratas/catkin_ws/src/ethzasl_xsens_driver-master/nodes/mtdevice.py", line 698, in read_measurement
    return self.parse_MTData(data, mode, settings)
  File "/home/ozgunkaratas/catkin_ws/src/ethzasl_xsens_driver-master/nodes/mtdevice.py", line 1155, in parse_MTData
    raise MTException("could not parse MTData message.")
mtdef.MTException: could not parse MTData message.
[xsens_driver-1] process has died [pid 9660, exit code 1, cmd /home/ozgunkaratas/catkin_ws/src/ethzasl_xsens_driver-master/nodes/mtnode.py __name:=xsens_driver __log:=/home/ozgunkaratas/.ros/log/d2f883be-2e81-11eb-921e-b0fc36b70e8b/xsens_driver-1.log].
log file: /home/ozgunkaratas/.ros/log/d2f883be-2e81-11eb-921e-b0fc36b70e8b/xsens_driver-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

I would appreciate any help and suggestions regarding this matter!

thank you,

Özgün

**Comment by ozgunkaratas** [comment]
Hey everybody, i want to close this issue since i found the solution, it lies on line 1150 of the script mtdevice.py where one 'b' is missing which should correspond to the number of values that the struct requires.
