### ISSUE TITLE
mtdef.MTException: unknown packet: 0xE09C.

### ISSUE THREAD

**Issue by Rezenders** [ethz-asl/ethzasl_xsens_driver#118]
Hello,

I am trying to run xsenx_driver in a raspberrypi3 but I get this type of error after a while.
The error msg is always changing but it is always a unknow packet. Any ideas what might be the problem?

```
Traceback (most recent call last):
  File "/home/pi/bluerov_ws/src/ethzasl_xsens_driver/nodes/mtnode.py", line 803, in <module>
    main()
  File "/home/pi/bluerov_ws/src/ethzasl_xsens_driver/nodes/mtnode.py", line 799, in main
    driver.spin()
  File "/home/pi/bluerov_ws/src/ethzasl_xsens_driver/nodes/mtnode.py", line 168, in spin
    self.spin_once()
  File "/home/pi/bluerov_ws/src/ethzasl_xsens_driver/nodes/mtnode.py", line 710, in spin_once
    data = self.mt.read_measurement()
  File "/home/pi/bluerov_ws/src/ethzasl_xsens_driver/nodes/mtdevice.py", line 700, in read_measurement
    return self.parse_MTData2(data)
  File "/home/pi/bluerov_ws/src/ethzasl_xsens_driver/nodes/mtdevice.py", line 1027, in parse_MTData2
    parse_status(data_id, content, ffmt))
  File "/home/pi/bluerov_ws/src/ethzasl_xsens_driver/nodes/mtdevice.py", line 968, in parse_status
    raise MTException("unknown packet: 0x%04X." % data_id)
mtdef.MTException: unknown packet: 0xE09C.
```

**Comment by peci1** [comment]
Try to configure the IMU to output just a Status Word or Status Byte types of status messages. It seems it publishes some status data this driver doesn't understand.
